dbfilename redis_cache.rdb
dir /home/user/rmg-bench/config/pids
pidfile /home/user/rmg-bench/config/pids/redis_cache.pid
bind 127.0.0.1
port 13003
maxmemory 784mb
maxmemory-policy allkeys-lru
appendonly no

save ""


aclfile /home/user/rmg-bench/config/redis_cache.acl
