dbfilename redis_queue.rdb
dir /home/user/rmg-bench/config/pids
pidfile /home/user/rmg-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11003

aclfile /home/user/rmg-bench/config/redis_queue.acl
